### ISSUE TITLE
Comparison with other VSCode extensions

### ISSUE THREAD

**Issue by ryepesg** [djplaner/memex#2]
This project seems to be addressing similar objectives as: https://github.com/dendronhq/dendron

A basic comparison between them could help to understand which use cases are being targeted by memex.

**Comment by djplaner** [comment]
Thanks for the pointer.   Dendron looks interesting.

However, memex is just a use of [Foam](https://foambubble.github.io/foam/).  A comparison between Foam and Dendron would more appropriate.
